services:
    stackrats-app:
        container_name: stackrats_app
        build:
            context: ./vendor/laravel/sail/runtimes/8.4
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.4/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
            - '${REVERB_SERVER_PORT:-8080}:8080'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - stackrats_net
        depends_on:
            - stackrats-mysql
            - stackrats-keydb
            - stackrats-mailpit
    stackrats-mysql:
        container_name: stackrats_db
        hostname: stackrats_db_host
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_EXTRA_OPTIONS: '${MYSQL_EXTRA_OPTIONS}'
        volumes:
            - 'stackrats-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - stackrats_net
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    stackrats-keydb:
        container_name: stackrats_keydb
        hostname: stackrats_keydb_host
        image: 'eqalpha/keydb:alpine'
        ports:
            - '${FORWARD_KEYDB_PORT:-6379}:6379'
        volumes:
            - 'stackrats-keydb:/data'
        command: ["keydb-server", "/etc/keydb/keydb.conf", "--appendonly", "yes"]
        networks:
            - stackrats_net
        healthcheck:
            test: ["CMD", "keydb-cli", "ping"]
            retries: 3
            timeout: 5s
    stackrats-mailpit:
        container_name: stackrats_mailpit
        hostname: stackrats_mailpit_host
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - stackrats_net
networks:
    stackrats_net:
        driver: bridge
        name: stackrats_net
volumes:
    stackrats-mysql:
        driver: local
    stackrats-keydb:
        driver: local
